name: Change

on:

  push:

    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "tele"

          replace: "TeamRyoishin"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Change it'

          commit_options: '--no-verify'

          repository: .

          commit_user_name: Ryoishin

          commit_user_email: ryoishincoder@gmail.com
          commit_author: Ryoishin <Ryoishin@users.noreply.github.com>
